version: '3'

services:
  postgres:
    image: postgres:14
    container_name: gtfs-postgres
    environment:
      POSTGRES_DB: gtfs_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pw
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/postgresql/data


